### ISSUE TITLE
event-countdown.js throws an error

### ISSUE THREAD

**Issue by marymar** [Moinworld/wtm-website#37]
`event-countdown.js:83 Uncaught TypeError: Cannot set property 'textContent' of null`
Occurs at moinworld.de

It's thrown because of html code which is commented out. See below:

``

**Comment by ilithya** [comment]
@marymar Yes, that was a tiny typo Anja did once, but it was not the real reason for our counter error.

Found out that the error had to do with getDate() function. Now we applied getUTCDate() and it works without the 1 extra day error. I believe we had to get the timestamp date with universal time. As now it's counting accurately.

If you'd like to go ahead, double check this on either our develop or master branches and comment on this before I close this issue.

Thanks! :)

**Comment by marymar** [comment]
The error occurred only in production.
with the dynamic counter it will not happen anymore.
